### ISSUE TITLE
wrong repeat unit

### ISSUE THREAD

**Issue by woodoo46** [giesselmann/STRique#10]
Hi STRique developers,

We have given wrong repeat unit in the repeat region, the program still output quite some results. Is this expected? For example, the expected repeat unit is CCGG we have given it ACTG, but the program still output repeat counts. Or, there is criteria other than prefix_score and suffix_score we can use to filter out?

Thanks.

George

**Comment by giesselmann** [comment]
Hi,
yes that's expected. STRique will do the best fit of signal and given repeat sequence between the flanking regions. Can't say what happens for completely mismatching repeats. 
We tested in simulations the impact of e.g. CGG repeats with sporadic AGG units. We couldn't see a difference in the overal repeat count.
However we can only count what's expected and can't detect mutations in the repeat.
