### ISSUE TITLE
Definitions of the output fields?

### ISSUE THREAD

**Issue by tchrisboles** [giesselmann/STRique#12]
I didn't find definitions of the fields in the output? 

ID, target, strand, seem obvious, but I'd like to know the definitions of the rest:
count (repeats, or bases?), score_prefix, score_suffix, log_p, offset, ticks, mod.

Thanks in advance.

Chris

**Comment by giesselmann** [comment]
Sure, that got lost in the transition to readthedocs. Update is going online.
