### ISSUE TITLE
Plot output using Docker

### ISSUE THREAD

**Issue by eblester** [giesselmann/STRique#13]
Hi Giesselmann, 

I’m currently trying to get the new Plot option to work. I managed to run the command without any error massages, but with no output file. Could you maybe help or see what might be wrong?

I used this command: cat /work/sdularsen/nanopore/04284circulomic_ligationkit_181119/04284circulomic_ligationkit_181119/04284circulomic/20191118_1413_1-E7-H7_PAE17010_81d9e4ee/fastq_pass/04284circulomic_ligationkit_181119_res.test.txt | python3 /app/scripts/STRique.py plot /work/sdularsen/nanopore/04284circulomic_ligationkit_181119/04284circulomic_ligationkit_181119/04284circulomic/20191118_1413_1-E7-H7_PAE17010_81d9e4ee/fast5_pass/reads.fofn

**Comment by giesselmann** [comment]
Hi,
The plot command should open an interactive window (matploglib).
Do you by chance use the Docker container? If so I'm already on it, it seems to be tricky to get graphical output out of the container.
I'll extend the command to also write output files, not sure how to handle the Docker yet.

**Comment by eblester** [comment]
Hi,
Yes I use the Docker container - so that's why. So it would be great if you could extend the command to write output files.
Thanks

**Comment by giesselmann** [comment]
Hi,
the updated plot command is on the way. The docker is still building, it will be available as version v0.4.2 soon. 
I'll close the issue after all builds passed.

**Comment by eblester** [comment]
Hi,
Thanks, it is now working and I’m getting output files with very nice plots.

**Comment by eblester** [comment]
Hi,

I wrote you about the plot function in STRique.

I was wondering if you could tell me about values on bath the x- and y-axis.

Kind regards
Emilie Lester

________________________________
Fra: Pay Gießelmann [notifications@github.com]
Sendt: 16. december 2019 17:02
Til: giesselmann/STRique
Cc: Emilie Boye Lester; Author
Emne: Re: [giesselmann/STRique] Plot output using Docker (#13)


Closed #13<https://github.com/giesselmann/STRique/issues/13>.

**Comment by giesselmann** [comment]
sure, x is time in ticks (currently the sampling rate of the MinION is 4k ticks per second) and y is the normalized raw signal.

**Comment by eblester** [comment]
Thank you, very helpful.

Do you know the time in ticks for PromethION (I did all my sampling on the PromethION)?


________________________________
Fra: Pay Gießelmann [notifications@github.com]
Sendt: 7. januar 2020 15:06
Til: giesselmann/STRique
Cc: Emilie Boye Lester; Author
Emne: Re: [giesselmann/STRique] Plot output using Docker (#13)


sure, x is time in ticks (currently the sampling rate of the MinION is 4k ticks per second) and y is the normalized raw signal.

**Comment by giesselmann** [comment]
No, but it's an attribute of the fast5 files. For the old single read ones it is:
/UniqueGlobalKey/context_tags/sample_frequency
For the new bulk format I guess it's somewhere in the read group.

You can use sth. like hdf5Compass to open the fast5.
