### ISSUE TITLE
Two issues to run STRique

### ISSUE THREAD

**Issue by liuqianhn** [giesselmann/STRique#15]
Hi @giesselmann ,

Glad to run your nice tool STRique. But I have two issues when running STRique on your plasmid_c9orf72 and my own data.

1. On plasmid_c9orf72, **STRique does not finish the running after 60 hours**. My command is given below
```
samtools view bam_results/barcode11.bam | python3 strique/0.4.0/scripts/STRique.py count strique_g4c2.fofn strique/0.4.0/models/r9_4_450bps.model strqiueg4c2.repeat_config.tsv > barcode11.strique.tsv
```
The repeat region I listed in `strqiueg4c2.repeat_config.tsv` is:
```
chr   begin end   name  repeat   prefix   suffix
pCRAmpBE 1111  1129  pCRAmpBEg4c2   GGGGCC   GATCCGCTCTTCCGGCC TGCGGCCGCCACCGCGG
```

2. On my own data for CAG repeat region, **I found that STRique cannot find reliable repeat counts in many reads. For example, I have ~4000 long reads, but STRique output 0 repeat count for ~1800 long reads, and many of other reads also have low score_prefix/score_suffix score.** My command is
```
samtools view htt_bam_results/barcode07.bam | python3 strique/0.4.0/scripts/STRique.py count htt.fofn strique/0.4.0/models/r9_4_450bps.model htt.repeat_config.tsv > barcode07.strique.tsv
```
The repeat region I listed in `htt.repeat_config.tsv` is:
```
chr   begin end   name  repeat   prefix   suffix
chr4  3074876  3074933  httCAG   CAG   AGTCCCTCAAGTCCTTC CAACAGCCGCCACCGCC
```

Could you please help to address the issues above? Thank you.

**Comment by giesselmann** [comment]
Hi,

To 1): 60h sounds quite long but depends of course on the number of reads. How many mapped reads are in 'barcode11.bam'? Can you run STRique with multiple cores (--t)? 
To 2): The prefix and suffix sequences you provide are in both examples very short. In the paper and also recommended in the docs is sth. like 150 Bp. The signal alignment for 17 Bp is likely not going to work.

In the paper I used

> pCRAmpBE	0	2912	pCRAmpBE	GGGGCC	CTGGCGAAAGGGGGATGTGCTGCAAGGCGATTAAGTTGGGTAACGCCAGGGTTTTCCCAGTCACGACGTTGTAAAACGACGGCCAGTGAGCGCGCGTAATACGACTCACTATAGGGCGAATTGGGTACCGGGGGATCCGCTCTTCCGGCC	TGCGGCCGCCACCGCGGTGGAGCTCCAGCTTTTGTTCCCTTTAGTGAGGGTTAATTGCGCGCTTGGCGTAATCATGGTCATAGCTGTTTCCTGTGTGAAATTGTTATCCGCTCACAATTCCACACAACATACGAGCCGGAAGCATAAAGT

For testing maybe try a subset of your data until you get reliable scores and counts.

Pay

**Comment by liuqianhn** [comment]
@giesselmann , thank you for your suggestion. I am going to try it.
1. It would be great if you can share how many cores you use for 1)
2. I will try `150 Bp` as you suggested.
3. I assume that `pCRAmpBE 0 2912` would be `pCRAmpBE 1111  1129`. Please correct me if I am wrong.

**Comment by giesselmann** [comment]
1. as many cores as you have available
2. perfect
3. should do the same job for the plasmid

**Comment by liuqianhn** [comment]
@giesselmann Thanks.
