### ISSUE TITLE
command plot is not recognised

### ISSUE THREAD

**Issue by BCArg** [giesselmann/STRique#16]
I have already used `index` and `count` commands from STRique and now I want to plot the results.

However, when I do `cat D144018.striqueFilter.tsv | python3 /app/scripts/STRique.py plot --output plotFilterD144018 index_D14418.fofn`

I get 

```
Unrecognized command
usage: STRique.py <command> [<args>]
Available commands are:
   index      Index batch(es) of bulk-fast5 or tar archived single fast5
   count      Count single read repeat expansions

STRique: a nanopore raw signal repeat detection pipeline

positional arguments:
  command     Subcommand to run

optional arguments:
  -h, --help  show this help message and exit
```

I am running STRique on a docker container (`Docker version 17.04.0-ce`) and docker setup was according to the [official documentation](https://strique.readthedocs.io/en/latest/installation/prerequisites/)

**Comment by giesselmann** [comment]
which version of the container do you have? Plotting was introduced in STRique 0.4.2, the output looks like an older version of the script is running.

**Comment by BCArg** [comment]
Thanks for the quick reply. In fact I was on version `0.3.0`. I am now on the `latest` version. The `plot` command is now recognised, though I am getting

```
Traceback (most recent call last):
  File "/app/scripts/STRique.py", line 1030, in <module>
    main()
  File "/app/scripts/STRique.py", line 890, in __init__
    getattr(self, args.command)(sys.argv[2:])
  File "/app/scripts/STRique.py", line 982, in plot
    ID, target, strand, count, score_prefix, score_suffix, _, offset, ticks = record[:9]
ValueError: not enough values to unpack (expected 9, got 1)
```

When I call `cat D144018.striqueFilter.tsv | python3 /app/scripts/STRique.py plot --output plotFilterD144018 index_D14418.fofn`

Does this have anything to do with the fact that I called `count` and `index` with another version of the container (`0.3.0`)? Shall I call these two commands with the `latest` version?

**Comment by giesselmann** [comment]
can you show the output of ```head D144018.striqueFilter.tsv``` ? 
The error indicates that the file has only one column, at least 9 are expected.
Feel free to mask/blacken the ID/count columns if the data is confidential.

**Comment by BCArg** [comment]
Oh the thing was that I manipulated the output (filter the colums `count`, `score_prefix` and `score_suffix)` with pandas and the resulting `df` was comma- (and not tab-) separated.

It appears to work now that my manipulated df is tab-delimited and after I removed the index column, which is present by default in pandas.

Thanks for the assistance

**Comment by giesselmann** [comment]
I'm happy to hear that. Closing this, but feel free to ask for further assistance.
