### ISSUE TITLE
No target found

### ISSUE THREAD

**Issue by idahoijer** [giesselmann/STRique#17]
Hi,

Thanks for a tool that I think could be very useful for me! Although I can't get it quite to work for my data.

I get "Not target found for.." every read in my data set, although I see in the genome browser that I have a large amount of reads mapped to my targeted repeat expansion. I use 150 bp prefix and suffix with a CAG repeat. Any idea what could be going on here? 

Thanks.

**Comment by giesselmann** [comment]
Hi,

"No target for {}" is raised if the mapped read position can't be intersected with any configured repeat location.
This either means the **read** begin/end are not outside of the **repeat** boundaries or
the read reference does not match the repeat reference e.g. 'chr1' vs. '1' vs. 'Chr1' .

**Comment by idahoijer** [comment]
Thanks for your very quick response. The reference match was indeed an issue, but even after correcting that I still do not get any reads containing the target. And I definitely have reads that spans the entire repeat. However, the cell line I am looking at (this sample was just run to see that the cas9 assay was working correctly) seem to have quite a bit shorter repeat than the reference and looking in IGV there is a deletion that spans most of the sequence within the repeat boundaries (I hope you understand what I mean). Does STRique maybe recognize this as the read ending or beginning within the boundaries then?

(Excuse my level of expertise. I am not a trained bioinformatian and is still learning).

**Comment by giesselmann** [comment]
What coordinates did you put in your STRique config file, the region or repeat only? 
Try the bp directly left/right of the repeat. See the config in this repo as reference, the distance for c9orf72 is only the 18 bp of the GGGGCC x3 itself.
Read coordinates are parsed from the .bam file, so if you see it in IGV over the repeat it should be noticed as such.
You can also set begin and end to some position where you see your reads in the browser. They have no other purpose than identifying reads spanning a target.

**Comment by idahoijer** [comment]
I eventually figured out what was wrong. The fofn file was not in the same directory as the fast5 files so now it is working. I figured it out while running the info flag instead of the debug flag for the log. Thanks a lot for your help, Pay!
