### ISSUE TITLE
Interpretation of results from STRique

### ISSUE THREAD

**Issue by bharathramh** [giesselmann/STRique#19]
We are doing repeat identification of (AAAAG)n/(AAGGG)n motifs (**region contains complex repeat patterns of both repeats**) on RFC1. 
We first tried on the example data of c9orf72 which is available on the docker container to understand the pipeline workflow. 

- although we were able to replicate the same plot as mentioned in the paper (we got 733 repeat counts). But, we couldn't understand the number of repeats getting calculated, as we were not able to find the GGGGCC / CCCCGG tandem repeats in the read from SAM file.

- And we tried our data with the reads which counted 44 repeats using STRique (plot attached), but expected to have more repeats. And we also couldn't understand the weird pattern in the repeat region. 

![RFC1_44_7162c73d-e984-433e-81d1-16d62c4f9396](https://user-images.githubusercontent.com/32830450/88150047-7e673680-cc1e-11ea-804c-9c6aa9939ef6.png)

And what are the smaller amplitude patterns denotes? 

- And how many reads and how much read length we have to sequence 500+ penta nucleotide repeats.. we devised our protocol around 3K purified PCR amplicons. what u suggest to get better output in STRique.

**Comment by giesselmann** [comment]
Hey,
- The sequence is in the SAM, but with errors. The repeat is GGCCCC here:
>CCCTGCCCTGGCCCCTGCCCGGCCCTGGCTGCCCC

- Visually I agree that the shown read should have more than 44 repeats. However the stalled pore in the middle and the shift of the read offset makes this one hard if not impossible to quantify. I wonder what the count distribution of the sample looks like.

- If I understand you correctly, your region contains both, AAAAG and AAGGG stretches? This might work with STRique as maybe the length of the peaks is the only difference in the signal of both STRs. 
But STRique was only designed to quantify a single STR sequence (either AAAAG or AAGGG) flanked by well known genomic sequence. If one would want to quantify/characterize the alternation of two STRs, a more complex HMM would be needed, allowing the algorithm to switch between repeat sequences.

- A few hundred reads on target should already be enough to get a good estimation of the repeat length. I wonder if the 500+ repeat length is still going through a PCR, we had already trouble with ~100 GGGGCC repeats. But this might be different depending on the sequence.

Pay

**Comment by bharathramh** [comment]
Hello Pay,
Thank you for the response. We were working based on your comments earlier. And have some more queries regarding this.

> Visually I agree that the shown read should have more than 44 repeats. However the stalled pore in the middle and the shift of the read offset makes this one hard if not impossible to quantify. I wonder what the count distribution of the sample looks like.
- _The count distribution of the sample is like, most of the reads having shorter read length (<600) giving 0 count (which we are thinking may be it didn't sequence suffix or prefix). And repeat counts increases from 3 to 44 as read length increases. However, only one read (length ~1 kb) was supporting 44 repeats._

**_Queries:_**

**Scenario:**  _Our data had around 120 bp prefix  and 200 bp suffix,and the repeats corresponding to 2.5Kb, so we designed to have PCR product of around 3k and stopped sequencing halfway since we got good amount of reads._
1. Do we need to change the protocol of sequencing longer reads say about 10k? or we should aim for more run time ? 

2. In the data we sequenced, only fewer reads having such longer read length, but during PCR we got for 3k band alone, but we are getting more number of shorter reads while sequencing. Have you ever encounter such issue while standardizing nanopore protocol.  

3. And we were trying to analysis the file you provided in supplementary of the paper 20171116_FAH31667_FLO-MIN106_SQK-LSK108_plasmid_c9orf72.tar.gz. But we couldn't find sample wise segregation of FAST5 files. Need clarification on that. So we can try to run the sample wise data and to understand the process to set up base pipeline.

**Comment by giesselmann** [comment]
Hi,
I'm sorry for the delay. To answer your scenario:
1. 120/200bp prefix/suffix is very short to frame 2.5kb of repeat sequence. I could imagine that our signal normalization will fail on these reads as 90% of the signal is repeat (See #9 the output for failed reads is 0). If possible I would recommend getting longer flanking sequences here.
2. We only used PCR on repeats < 100 (600bp), I can't tell how good this works on longer repeats. There might be a bias in the pore against longer repeats, we usually sequenced more reads from the wild type allele, compared to the expanded one.
3. Sample info is given with the upload (https://figshare.com/articles/STRique_repeat_detection_data/7205666). You'll need to run basecalling and barcode de-multiplexing to segregate samples.

Pay
