### ISSUE TITLE
ModuleNotFoundError: No module named 'ont_fast5_api'

### ISSUE THREAD

**Issue by Tine-dk** [giesselmann/STRique#23]
Hi,

I get the following error:
`ModuleNotFoundError: No module named 'ont_fast5_api'`

I have installed STRique according to the installation guide for source installation and things seemed to work just fine except I had to install pomegranate with pip as the requirements.txt failed for that one. 

It seems like I do have a submodule names 'ont_fast5_api' since I have the following:
`~/src/STRique/submodules/ont_fast5_api/ont_fast5_api`

Can you help me out?

I also installed STRique with udocker in a different env but the creation of fofn files seems never-ending.

**Comment by giesselmann** [comment]
Hi,

Which command is causing the error?

Can you post the error you had when installing from the requirements.txt?
The pomegranate version is crucial, others seem to break in combination with networkx and our code.

The files in the submodules folder alone are not sufficient, they should become installed by the
>pip3 install -r requirements.txt

Pay
