### ISSUE TITLE
Documentation for Fast5Masker (expansion request)

### ISSUE THREAD

**Issue by ChristianJP** [giesselmann/STRique#26]
Hello,

Is it possible for you to submit some documentation/usage for fast5masker.py script, I am attempting to mask some data and similarily to your Nanopolish step, then run the raw signal through megalodon.

Thanks

**Comment by giesselmann** [comment]
Hi,
I updated the docs with a section about masking.
I re-wrote the masker script to make it easier to use, please fetch the latest commit to get it.

Builds are currently failing for another reason, pomegranate doesn't want to be installed.

Cheers,
Pay
