### ISSUE TITLE
Explanation needed for model files

### ISSUE THREAD

**Issue by liutiming** [giesselmann/STRique#6]
Thanks for the tool!

I can understand r9_4 and 450bps are both parameters of the nanopore. What about mCpG? Also can I ask where I will be able to obtain .model files for other nanopore models? For example, we have some experiment planned for R10. 

Thanks!

**Comment by giesselmann** [comment]
Hey,
r9_4_450bps.model is the pore model for unmodified DNA and usally your choice. r9_4_450bps.model_mCpG is the model for 5mC methylation in CpG contexts. Methylation detection on the repeat is still in development why I'm not yet documenting it.
The models are build in-house, but similar to the ones provided by ONT (https://github.com/nanoporetech/kmer_models) 
As soon as we have R10 models available, I will add them to the repository.
Pay

**Comment by renzilin** [comment]
Can I use the r9_4_450bps.model on the data from r9.4.1 ?
If I can't, could provide me with r9.4.1 model file? Thanks!

**Comment by giesselmann** [comment]
Yes, 9.4.1 didn't change the signal. R10 won't work though.

**Comment by renzilin** [comment]
> Yes, 9.4.1 didn't change the signal. R10 won't work though.

Thanks for your quick reply!
