### ISSUE TITLE
prefix/suffix in repeat_config.tsv

### ISSUE THREAD

**Issue by woodoo46** [giesselmann/STRique#8]

**Comment by woodoo46** [comment]
Hi STRique developers,

I am just wondering if there is a specific rule for setting up the prefix/suffix columns in repeat_config.tsv file?

Thanks.

**Comment by giesselmann** [comment]
Hi,
I updated the docs today, not sure if you've seen it already. https://strique.readthedocs.io/en/latest/
prefix and suffix are the sequences directly before and after the repeat, seen from template strand.
150Bp is usally a good length.
